# -*- coding: utf-8 -*-
"""energy_meter_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQfhwQBXx7E13_ZbdpSMTHN6hDlTZKt2
"""

# energy_meter_simulator.py

import random
import csv
import time

def generate_energy_data(num_records):
    """Generate random energy consumption data."""
    data = []
    for _ in range(num_records):
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        consumption = round(random.uniform(0, 100), 2)  # Random consumption between 0 and 100 kWh
        data.append((timestamp, consumption))
        time.sleep(1)  # Simulate time delay between readings (optional)
    return data

def save_to_csv(data, filename):
    """Save the generated data to a CSV file."""
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Timestamp', 'Energy Consumption (kWh)'])  # Header
        writer.writerows(data)

def main():
    num_records = int(input("Enter the number of records to generate: "))
    filename = 'energy_consumption_data.csv'

    print(f"Generating {num_records} records...")
    energy_data = generate_energy_data(num_records)

    save_to_csv(energy_data, filename)
    print(f"Data saved to {filename}")

if __name__ == "__main__":
    main()